using BannerKings;
using BannerKings.Managers.Education.Languages;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated0;
using TaleWorlds.ObjectSystem;

namespace BannerKings1259.Languages
{
    public class AD1259Languages : DefaultTypeInitializer<AD1259Languages, Language>
    {
        public Language Latin { get; } = new Language("language_latin");
        public Language ByzantineGreek { get; } = new Language("byzantine_greek");
        public Language WesternArabic { get; } = new Language("westernarabic");
        public Language EastSlavic { get; } = new Language("east_slavic");
        public Language French { get; } = new Language("french");
        public Language English { get; } = new Language("english");
        public Language German { get; } = new Language("german");
        public Language Polish { get; } = new Language("polish");
        public Language Lithuanian { get; } = new Language("lithuanian");
        public Language Czech { get; } = new Language("czech");
        public Language Hungarian { get; } = new Language("hungarian");
        public Language Serbian { get; } = new Language("serbian");
        public Language Bosnian { get; } = new Language("bosnian");
        public Language Bulgharian { get; } = new Language("bulgharian");
        public Language Georgian { get; } = new Language("georgian");
        public Language Armenian { get; } = new Language("armenian");
        public Language Turkish { get; } = new Language("turkish");
        public Language Kipchak { get; } = new Language("kipchak");
        public Language Persian { get; } = new Language("persian");
        public Language Castillian { get; } = new Language("castillian");
        public Language Aragonese { get; } = new Language("aragonese");
        public Language Portugeese { get; } = new Language("portugeese");
        public Language Welsh { get; } = new Language("welsh");
        public Language Gealic { get; } = new Language("gealic");
        public Language Scottish { get; } = new Language("scottish");
        public Language Danish { get; } = new Language("danish");
        public Language Swedish { get; } = new Language("swedish");
        public Language Norse { get; } = new Language("norse");
        public Language Saami { get; } = new Language("saami");

        public override IEnumerable<Language> All
        {
            get
            {
                yield return Latin;
                yield return ByzantineGreek;
                yield return WesternArabic;
                yield return EastSlavic;
                yield return French;
                yield return German;
                yield return English;
                yield return Polish;
                yield return Lithuanian;
                yield return Czech;
                yield return Hungarian;
                yield return Serbian;
                yield return Bosnian;
                yield return Bulgharian;
                yield return Georgian;
                yield return Armenian;
                yield return Turkish;
                yield return Kipchak;
                yield return Persian;
                yield return Castillian;
                yield return Aragonese;
                yield return Portugeese;
                yield return Welsh;
                yield return Gealic;
                yield return Scottish;
                yield return Danish;
                yield return Swedish;
                yield return Norse;
                yield return Saami;
            }
        }
        public override void Initialize()
        {
            //var cultures = Game.Current.ObjectManager.GetObjectTypeList<CultureObject>();
            CultureObject aragonese = MBObjectManager.Instance.GetObject<CultureObject>("aragonese");
            CultureObject armenia = MBObjectManager.Instance.GetObject<CultureObject>("armenia");
            CultureObject baltic = MBObjectManager.Instance.GetObject<CultureObject>("baltic");
            CultureObject berber = MBObjectManager.Instance.GetObject<CultureObject>("aserai");
            CultureObject bohemia = MBObjectManager.Instance.GetObject<CultureObject>("bohemia");
            CultureObject bosnia = MBObjectManager.Instance.GetObject<CultureObject>("bosnia");
            CultureObject bulgaria = MBObjectManager.Instance.GetObject<CultureObject>("bulgaria");
            CultureObject castile = MBObjectManager.Instance.GetObject<CultureObject>("castile");
            CultureObject crusader = MBObjectManager.Instance.GetObject<CultureObject>("crusader");
            CultureObject danish = MBObjectManager.Instance.GetObject<CultureObject>("danish");
            CultureObject england = MBObjectManager.Instance.GetObject<CultureObject>("england");
            CultureObject france = MBObjectManager.Instance.GetObject<CultureObject>("vlandia");
            CultureObject gealic = MBObjectManager.Instance.GetObject<CultureObject>("battania");
            CultureObject georgia = MBObjectManager.Instance.GetObject<CultureObject>("georgia");
            CultureObject germanic = MBObjectManager.Instance.GetObject<CultureObject>("germanic");
            CultureObject andalus = MBObjectManager.Instance.GetObject<CultureObject>("andalus");
            CultureObject greek = MBObjectManager.Instance.GetObject<CultureObject>("greek");
            CultureObject halych = MBObjectManager.Instance.GetObject<CultureObject>("halych");
            CultureObject hungarian = MBObjectManager.Instance.GetObject<CultureObject>("hungarian");
            CultureObject ilkhanid = MBObjectManager.Instance.GetObject<CultureObject>("ilkhanid");
            CultureObject italian = MBObjectManager.Instance.GetObject<CultureObject>("empire");
            CultureObject latin = MBObjectManager.Instance.GetObject<CultureObject>("latin");
            CultureObject darshi = MBObjectManager.Instance.GetObject<CultureObject>("darshi");
            CultureObject cuman = MBObjectManager.Instance.GetObject<CultureObject>("cuman");
            CultureObject genoa = MBObjectManager.Instance.GetObject<CultureObject>("genoa");
            CultureObject santiago = MBObjectManager.Instance.GetObject<CultureObject>("santiago");
            CultureObject templar = MBObjectManager.Instance.GetObject<CultureObject>("templar");
            CultureObject sami = MBObjectManager.Instance.GetObject<CultureObject>("sami");
            CultureObject nizari = MBObjectManager.Instance.GetObject<CultureObject>("nizari");
            CultureObject lazarus = MBObjectManager.Instance.GetObject<CultureObject>("lazarus");
            CultureObject cathars = MBObjectManager.Instance.GetObject<CultureObject>("cathars");
            CultureObject hospitaller = MBObjectManager.Instance.GetObject<CultureObject>("hospitaller");
            CultureObject mongolian = MBObjectManager.Instance.GetObject<CultureObject>("khuzait");
            CultureObject norwegian = MBObjectManager.Instance.GetObject<CultureObject>("norwegian");
            CultureObject poland = MBObjectManager.Instance.GetObject<CultureObject>("poland");
            CultureObject portuguese = MBObjectManager.Instance.GetObject<CultureObject>("portuguese");
            CultureObject rus = MBObjectManager.Instance.GetObject<CultureObject>("rus");
            CultureObject scottish = MBObjectManager.Instance.GetObject<CultureObject>("scottish");
            CultureObject serbia = MBObjectManager.Instance.GetObject<CultureObject>("serbia");
            CultureObject sweden = MBObjectManager.Instance.GetObject<CultureObject>("sturgia");
            CultureObject teutonic = MBObjectManager.Instance.GetObject<CultureObject>("teutonic");
            CultureObject turkish = MBObjectManager.Instance.GetObject<CultureObject>("turkish");
            CultureObject wales = MBObjectManager.Instance.GetObject<CultureObject>("wales");

            MBReadOnlyList<CultureObject> cultures =
            Game.Current.ObjectManager.GetObjectTypeList<CultureObject>();

            List<CultureObject> validCultures = new List<CultureObject>();
            foreach (var culture in cultures)
            {
                if (!culture.IsBandit)
                {
                    validCultures.Add(culture);
                }
            }

            if (!validCultures.Any())
            {
                throw new MBException("No cultures were found");
            }



            this.Latin.Initialize(new TextObject("Latin"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { italian, templar, lazarus, genoa },
                                  this.GetIntelligibles(Latin));

            this.ByzantineGreek.Initialize(new TextObject("Byzantine Greek"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { greek, latin },
                                  this.GetIntelligibles(ByzantineGreek));

            this.WesternArabic.Initialize(new TextObject("Western Arabic"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { andalus, berber, nizari, darshi },
                                  this.GetIntelligibles(WesternArabic));

            this.EastSlavic.Initialize(new TextObject("East Slavic"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { halych, rus },
                                  this.GetIntelligibles(EastSlavic));

            this.French.Initialize(new TextObject("French"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { france, crusader, hospitaller, cathars },
                                  this.GetIntelligibles(French));

            this.English.Initialize(new TextObject("English"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { england },
                                  this.GetIntelligibles(English));

            this.German.Initialize(new TextObject("German"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { germanic, teutonic },
                                  this.GetIntelligibles(German));

            this.Polish.Initialize(new TextObject("Polish"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { poland },
                                  this.GetIntelligibles(Polish));

            this.Lithuanian.Initialize(new TextObject("Lithuanian"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { baltic },
                                  this.GetIntelligibles(Lithuanian));

            this.Czech.Initialize(new TextObject("Czech"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { bohemia },
                                  this.GetIntelligibles(Czech));

            this.Hungarian.Initialize(new TextObject("Hungarian"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { hungarian },
                                  this.GetIntelligibles(Hungarian));

            this.Serbian.Initialize(new TextObject("Serbian"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { serbia },
                                  this.GetIntelligibles(Serbian));

            this.Bosnian.Initialize(new TextObject("Bosnian"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { bosnia },
                                  this.GetIntelligibles(Bosnian));

            this.Bulgharian.Initialize(new TextObject("Bulgharian"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { bulgaria },
                                  this.GetIntelligibles(Bulgharian));

            this.Georgian.Initialize(new TextObject("Georgian"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { georgia },
                                  this.GetIntelligibles(Georgian));

            this.Armenian.Initialize(new TextObject("Armenian"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { armenia },
                                  this.GetIntelligibles(Armenian));

            this.Turkish.Initialize(new TextObject("Turkish"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { turkish },
                                  this.GetIntelligibles(Turkish));

            this.Kipchak.Initialize(new TextObject("Kipchak Turkish"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { mongolian, cuman },
                                  this.GetIntelligibles(Kipchak));

            this.Persian.Initialize(new TextObject("Persian"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { ilkhanid },
                                  this.GetIntelligibles(Persian));

            this.Aragonese.Initialize(new TextObject("Aragonese"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { aragonese },
                                  this.GetIntelligibles(Aragonese));

            this.Castillian.Initialize(new TextObject("Castillian"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { castile, santiago },
                                  this.GetIntelligibles(Castillian));

            this.Portugeese.Initialize(new TextObject("Portugeese"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { portuguese },
                                  this.GetIntelligibles(Portugeese));

            this.Welsh.Initialize(new TextObject("Welsh"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { wales },
                                  this.GetIntelligibles(Welsh));

            this.Gealic.Initialize(new TextObject("Gealic"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { gealic },
                                  this.GetIntelligibles(Gealic));

            this.Scottish.Initialize(new TextObject("Portugeese"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { scottish },
                                  this.GetIntelligibles(Scottish));

            this.Danish.Initialize(new TextObject("Danish"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { danish },
                                  this.GetIntelligibles(Danish));

            this.Swedish.Initialize(new TextObject("Swedish"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { sweden },
                                  this.GetIntelligibles(Swedish));

            this.Norse.Initialize(new TextObject("Norse"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { norwegian },
                                  this.GetIntelligibles(Norse));

            this.Saami.Initialize(new TextObject("Sámi"),
                                  new TextObject("Latin language..."),
                                  new List<CultureObject> { sami },
                                  this.GetIntelligibles(Saami));



            foreach (Language lang in this.All)
            {
                DefaultLanguages.Instance.AddObject(lang);
            }
        }

        private Dictionary<Language, float> GetIntelligibles(Language language)
        {
            switch (language.StringId)
            {
                case "some_language":
                    return new Dictionary<Language, float> { };

                default:
                    return new Dictionary<Language, float>();
            }
        }
    }
}
